[package]
name = "wttrbar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.24"
pad = "0.1.6"
reqwest = { version = "0.11.16", features = ["blocking", "json"] }
serde_json = "1.0.96"

[[bin]]
name = "wttrbar"
path = "main.rs"
