[package]
name = "wttrbar"
version = "0.10.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.34"
clap = { version = "4.5.1", features = ["derive"] }
reqwest = { version = "0.11.24", default-features = false, features = ["blocking", "json", "rustls-tls"] }
serde_json = "1.0.96"

